version: "3.9"

services:
  vkbot:
    build: .
    container_name: vk_video_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./videos:/app/videos
      - ./cookies.txt:/app/cookies.txt